name: CD - Deploy React Frontend

on:
  #To see the Run workflow button, your workflow file must use the workflow_dispatch event trigger.
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - frontend/react/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/react

    steps:
      # actions/checkout@v2, which is the action that checked out
      # your repository to the computer that runs the action.
      # It is used to check-out a repo so a workflow can access it.
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set generated build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT

      - name: Docker Build and push
        run: |
          chmod +x ../../.ci/build-publish.sh
          USERNAME=bogdash \
          REPO=customer-react \
          TAG=${{ steps.build-number.outputs.BUILD_NUMBER }}